apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - backendconfig.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: us-central1-docker.pkg.dev/clgcporg10-178/ehc-app/tasky
    newTag: REPLACE_WITH_GIT_SHA
